import { companyRegistry } from '../src/data/companyRegistry.js';

const OUTPUT_PATH = new URL('../src/data/liveMarketSnapshot.js', import.meta.url);
const WINDOW_DAYS = 30;
const CONCURRENCY = 8;
const MAX_ITEMS = 10;

const EVENT_PATTERNS = Object.freeze({
  fundingMentions: /(инвестиц|раунд|финансирован|привлек|привлеч|funding|investment|round|million|млн|млрд)/i,
  dealMentions: /(сделк|партнер|партнёр|контракт|клиент|collaboration|partnership|deal|customer|agreement)/i,
  launchMentions: /(запуст|релиз|новый продукт|новую версию|launch|release|product)/i,
  tractionMentions: /(пользовател|клиент|выручк|оборот|employees|сотрудник|транзакц|users|revenue)/i,
});

function decodeXml(value = '') {
  return String(value)
    .replace(/<!\[CDATA\[/g, '')
    .replace(/\]\]>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code)))
    .trim();
}

function tag(block, name) {
  const match = block.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)</${name}>`, 'i'));
  return decodeXml(match?.[1] || '');
}

function normalizeTitle(value) {
  return value.toLowerCase().replace(/[^\\p{L}\\p{N}]+/gu, ' ').trim();
}

function parseItems(xml) {
  return [...xml.matchAll(/<item>[\\s\\S]*?<\\/item>/gi)]
    .map((match) => match[0])
    .map((block) => ({
      title: tag(block, 'title'),
      url: tag(block, 'link'),
      publishedAt: tag(block, 'pubDate'),
      sourceName: tag(block, 'source'),
      description: tag(block, 'description'),
    }))
    .filter((item) => item.title && item.url)
    .slice(0, MAX_ITEMS);
}

async function fetchCompany(company) {
  const query = encodeURIComponent(`"${company.name}" ИИ`);
  const url = `https://news.google.com/rss/search?q=${query}&hl=ru&gl=RU&ceid=RU:ru`;
  const response = await fetch(url, {
    headers: { 'User-Agent': 'FORDEX-Live-Market/1.0 (+https://github.com/borzenkoofficial-lab/FORDEX)' },
  });
  if (!response.ok) throw new Error(`RSS ${response.status}`);
  const items = parseItems(await response.text());
  const now = Date.now();
  const cutoff30 = now - WINDOW_DAYS * 24 * 60 * 60 * 1000;
  const cutoff7 = now - 7 * 24 * 60 * 60 * 1000;
  const seen = new Set();
  const recent = [];

  for (const item of items) {
    const publishedMs = Date.parse(item.publishedAt);
    if (!Number.isFinite(publishedMs) || publishedMs < cutoff30) continue;
    const key = normalizeTitle(item.title) + '|' + item.url;
    if (seen.has(key)) continue;
    seen.add(key);
    recent.push({ ...item, publishedMs });
  }

  const ordered = recent.sort((a, b) => b.publishedMs - a.publishedMs);
  const combined = ordered.map((item) => `${item.title} ${item.description}`).join(' ');

  return {
    sourceCount30d: ordered.length,
    sourceCount7d: ordered.filter((item) => item.publishedMs >= cutoff7).length,
    fundingMentions: ordered.filter((item) => EVENT_PATTERNS.fundingMentions.test(`${item.title} ${item.description}`)).length,
    dealMentions: ordered.filter((item) => EVENT_PATTERNS.dealMentions.test(`${item.title} ${item.description}`)).length,
    launchMentions: ordered.filter((item) => EVENT_PATTERNS.launchMentions.test(`${item.title} ${item.description}`)).length,
    tractionMentions: ordered.filter((item) => EVENT_PATTERNS.tractionMentions.test(`${item.title} ${item.description}`)).length,
    latestPublishedAt: ordered[0]?.publishedAt || null,
    latestTitle: ordered[0]?.title || null,
    latestUrl: ordered[0]?.url || null,
    latestSourceName: ordered[0]?.sourceName || null,
    sources: ordered.slice(0, 5).map(({ title, url, publishedAt, sourceName }) => ({
      title,
      url,
      publishedAt,
      sourceName: sourceName || null,
    })),
  };
}

async function mapWithConcurrency(items, worker, concurrency) {
  const results = new Array(items.length);
  let cursor = 0;
  async function run() {
    while (true) {
      const index = cursor++;
      if (index >= items.length) return;
      try {
        results[index] = await worker(items[index]);
      } catch (error) {
        results[index] = {
          sourceCount30d: 0,
          sourceCount7d: 0,
          fundingMentions: 0,
          dealMentions: 0,
          launchMentions: 0,
          tractionMentions: 0,
          latestPublishedAt: null,
          latestTitle: null,
          latestUrl: null,
          latestSourceName: null,
          sources: [],
          error: error instanceof Error ? error.message : 'FETCH_FAILED',
        };
      }
    }
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, run));
  return results;
}

function serialize(snapshot) {
  return `// Generated by scripts/refresh-market.mjs. Do not edit manually.\nexport const LIVE_MARKET_SNAPSHOT_VERSION = '1.0';\n\nexport const liveMarketSnapshot = ${JSON.stringify(snapshot, null, 2)};\n\nexport function getLiveMarketSignal(companyId) {\n  return liveMarketSnapshot.companies[companyId] ?? null;\n}\n`;
}

const rankedCompanies = companyRegistry
  .filter((item) => item.kind === 'INDEX COMPANY' || item.kind === 'EMERGING STARTUP')
  .sort((a, b) => {
    const aPriority = a.kind === 'INDEX COMPANY' ? 0 : 1;
    const bPriority = b.kind === 'INDEX COMPANY' ? 0 : 1;
    return aPriority - bPriority || a.name.localeCompare(b.name);
  })
  .slice(0, 80);

const rows = await mapWithConcurrency(
  rankedCompanies,
  async (company) => fetchCompany(company),
  CONCURRENCY,
);

const companies = Object.fromEntries(rankedCompanies.map((company, index) => [
  company.id,
  { companyId: company.id, companyName: company.name, ...rows[index] },
]));

const snapshot = {
  generatedAt: new Date().toISOString(),
  windowDays: WINDOW_DAYS,
  source: 'Google News RSS discovery',
  companies,
};

const { writeFile } = await import('node:fs/promises');
await writeFile(OUTPUT_PATH, serialize(snapshot), 'utf8');
